### ISSUE TITLE
RCM processing are in error

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/grdwindinversion#22]
```bash
python main.py --input_file /home/datawork-cersat-public/provider/asc-csa/satellite/l1/rcm/rcm3/SCLNC/GRD/2023/137/RCM3_OK2554779_PK2560509_1_SCLNC_20230517_132957_VV_VH_GRD/ --outputdir /tmp/
```

# traceback:
```python
10/07/2023 12:00:44 INFO schemas.py(1234) Resource 'XMLSchema.xsd' is already loaded                                                                                                                          
/opt/conda-envs/dev/lib/python3.10/site-packages/safe_rcm/product/reader.py:59: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be rela
xed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to 
the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
  {"timeStamp": ds["timeStamp"].astype("datetime64")}                                                                                                                                                         
/opt/conda-envs/dev/lib/python3.10/site-packages/safe_rcm/product/reader.py:68: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be rela
xed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to 
the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.                                              
  {"timeStamp": ds["timeStamp"].astype("datetime64")}                                                                                                                                                         
10/07/2023 12:00:48 ERROR io.py(224) FilePath is currently a read-only interface.                                                                                                                             
10/07/2023 12:00:48 ERROR io.py(224) FilePath is currently a read-only interface.                                                                                                                             
10/07/2023 12:00:48 ERROR io.py(224) File-like object not found in virtual filesystem: b'4c0b12dc-4cb1-44b9-9279-d1232838c090/4c0b12dc-4cb1-44b9-9279-d1232838c090.aux'
10/07/2023 12:00:48 ERROR io.py(224) File-like object not found in virtual filesystem: b'4c0b12dc-4cb1-44b9-9279-d1232838c090/4c0b12dc-4cb1-44b9-9279-d1232838c090.AUX'
10/07/2023 12:00:48 ERROR io.py(224) File-like object not found in virtual filesystem: b'4c0b12dc-4cb1-44b9-9279-d1232838c090/4c0b12dc-4cb1-44b9-9279-d1232838c090.aux'
10/07/2023 12:00:48 ERROR io.py(224) File-like object not found in virtual filesystem: b'4c0b12dc-4cb1-44b9-9279-d1232838c090/4c0b12dc-4cb1-44b9-9279-d1232838c090.AUX'
10/07/2023 12:00:48 ERROR io.py(224) FilePath is currently a read-only interface.
10/07/2023 12:00:48 ERROR io.py(224) FilePath is currently a read-only interface.
10/07/2023 12:00:48 ERROR io.py(224) File-like object not found in virtual filesystem: b'f8fbcc5c-b210-4bd0-9597-7bd55b111071/f8fbcc5c-b210-4bd0-9597-7bd55b111071.aux'
10/07/2023 12:00:48 ERROR io.py(224) File-like object not found in virtual filesystem: b'f8fbcc5c-b210-4bd0-9597-7bd55b111071/f8fbcc5c-b210-4bd0-9597-7bd55b111071.AUX'
10/07/2023 12:00:48 ERROR io.py(224) File-like object not found in virtual filesystem: b'f8fbcc5c-b210-4bd0-9597-7bd55b111071/f8fbcc5c-b210-4bd0-9597-7bd55b111071.aux'
10/07/2023 12:00:48 ERROR io.py(224) File-like object not found in virtual filesystem: b'f8fbcc5c-b210-4bd0-9597-7bd55b111071/f8fbcc5c-b210-4bd0-9597-7bd55b111071.AUX'
Traceback (most recent call last):
  File "/home1/datahome/agrouaze/sources/git/grdwindinversion/grdwindinversion/main.py", line 48, in <module>
    out_file = makeL2(input_file, out_folder, config_file,overwrite=args.overwrite)
  File "/home1/datahome/agrouaze/sources/git/grdwindinversion/grdwindinversion/inversion.py", line 120, in makeL2
    meta = fct_meta(filename)
  File "/home1/datahome/agrouaze/sources/git/xsar/src/xsar/utils.py", line 94, in wrapper
    result = f(*args, **kwargs)
  File "/home1/datahome/agrouaze/sources/git/xsar/src/xsar/rcm_meta.py", line 93, in __init__
    self.manifest_attrs = self._create_manifest_attrs()
  File "/home1/datahome/agrouaze/sources/git/xsar/src/xsar/rcm_meta.py", line 196, in _create_manifest_attrs
    dic["swath_type"] = os.path.basename(self.path).split('_')[4]
IndexError: list index out of range

```

**Comment by vincelhx** [comment]
closed; 
can handle single or dualpol 
can handle RCM
