### ISSUE TITLE
Some imports do not work

### ISSUE THREAD

**Issue by Skealz** [umr-lops/grdwindinversion#30]
```
SAR_L1-to-L2_wind_processor --input_file /home/datawork-cersat-public/cache/project/sarwing/data/RS2/L1/VV_VH/2022/248/RS2_OK141302_PK1242225_DK1208539_SCWA_20220905_212400_VV_VH_SGF --output_dir ./output_tests/
Traceback (most recent call last):
  File "/home/datawork-cersat-public/cache/project/sarwing/users/tcevaer/chain/l1_inversion_pip_env/bin/SAR_L1-to-L2_wind_processor", line 5, in <module>
    from grdwindinversion.main import processor_starting_point
  File "/home/datawork-cersat-public/cache/project/sarwing/users/tcevaer/grdwindinversion/grdwindinversion/__init__.py", line 7, in <module>
    from grdwindinversion import *
  File "/home/datawork-cersat-public/cache/project/sarwing/users/tcevaer/grdwindinversion/grdwindinversion/inversion.py", line 17, in <module>
    from load_config import getConf
ModuleNotFoundError: No module named 'load_config'
```

**Comment by Skealz** [comment]
Same for 
```
from .inversion import makeL2_tempo_Vinc
from .utils import get_memory_usage
```
in main.py

and 
`from grdwindinversion import *` in __init__.py that leads to circular import
