### ISSUE TITLE
Calling main script without config does not work (but it should following the args doc)

### ISSUE THREAD

**Issue by Skealz** [umr-lops/grdwindinversion#34]
```
$ SAR_L1-to-L2_wind_processor --input_file /home/datawork-cersat-public/cache/project/sarwing/data/RS2/L1/VV_VH/2022/248/RS2_OK141302_PK1242225_DK1208539_SCWA_20220905_212400_VV_VH_SGF --outputdir ./output_tests/
05/09/2023 16:46:29 INFO main.py(34) input file: /home/datawork-cersat-public/cache/project/sarwing/data/RS2/L1/VV_VH/2022/248/RS2_OK141302_PK1242225_DK1208539_SCWA_20220905_212400_VV_VH_SGF
Traceback (most recent call last):
  File "/home/datawork-cersat-public/cache/project/sarwing/users/tcevaer/chain/l1_inversion_pip_env/bin/SAR_L1-to-L2_wind_processor", line 8, in <module>
    sys.exit(processor_starting_point())
  File "/home/datawork-cersat-public/cache/project/sarwing/users/tcevaer/grdwindinversion/grdwindinversion/main.py", line 55, in processor_starting_point
    out_file = makeL2(input_file, out_folder, config_file, overwrite=args.overwrite)
  File "/home/datawork-cersat-public/cache/project/sarwing/users/tcevaer/grdwindinversion/grdwindinversion/inversion.py", line 121, in makeL2
    raise FileNotFoundError('config_path do not exists, got %s ' % config_path)
FileNotFoundError: config_path do not exists, got config_RS2.yaml 
```

In the parser it says :
```
    parser.add_argument('--config_file',
                        help='config file path [if not provided will take config file based on input file]',
```

**Comment by agrouaze** [comment]
closed with #36
