### ISSUE TITLE
TIFF error TIFFReadDirectory:Failed to read directory at offset

### ISSUE THREAD

**Issue by Skealz** [umr-lops/grdwindinversion#53]
When processing
S1A_EW_GRDM_1SDV_20210930T205405_20210930T205434_039916_04B935_B159.SAFE

```python
11/02/2024 18:56:11 INFO init.py(304) GDAL signalled an error: err_no=1, msg='s1a-ew-grd-vv-20210930t205405-20210930t205434-039916-04b935-001.tiff: TIFFFetchDirectory:/home/datawork-cersat-public/cache/project/mpc-sentinel1/data/esa/sentinel-1a/L1/EW/S1A_EW_GRDM_1S/2021/273/S1A_EW_GRDM_1SDV_20210930T205405_20210930T205434_039916_04B935_B159.SAFE/measurement/s1a-ew-grd-vv-20210930t205405-20210930t205434-039916-04b935-001.tiff: Can not read TIFF directory count'
11/02/2024 18:56:11 INFO init.py(304) GDAL signalled an error: err_no=1, msg='s1a-ew-grd-vv-20210930t205405-20210930t205434-039916-04b935-001.tiff: TIFFReadDirectory:Failed to read directory at offset 102684056'
11/02/2024 18:56:11 INFO inversion.py(493) Traceback (most recent call last):
  File "rasterio/base.pyx", line 310, in rasterio.base.DatasetBase.__init
  File "rasterio/_base.pyx", line 221, in rasterio._base.open_dataset
  File "rasterio/_err.pyx", line 221, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_AppDefinedError: s1a-ew-grd-vv-20210930t205405-20210930t205434-039916-04b935-001.tiff: TIFFReadDirectory:Failed to read directory at offset 102684056

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/2024v2v1_0v9_0v2v3vpost6_1v0v7_1v0v6_1v0v5_1v1v11_1v0v1_1v0v1/grdwindinversion/lib/python3.10/site-packages/grdwindinversion/inversion.py", line 476, in makeL2
    xsar_dataset = fct_dataset(meta, resolution=resolution,recalibration=recalibration)
  File "/tmp/2024v2v1_0v9_0v2v3vpost6_1v0v7_1v0v6_1v0v5_1v1v11_1v0v1_1v0v1/grdwindinversion/lib/python3.10/site-packages/xsar/sentinel1_dataset.py", line 135, in init
    self.resolution, DN_tmp = self.sar_meta.reader.load_digital_number(resolution=resolution,
  File "/tmp/2024v2v1_0v9_0v2v3vpost6_1v0v7_1v0v6_1v0v5_1v1v11_1v0v1_1v0v1/grdwindinversion/lib/python3.10/site-packages/safe_s1/metadata.py", line 179, in load_digital_number
    rio = rasterio.open(files_measurement[0])
  File "/tmp/2024v2v1_0v9_0v2v3vpost6_1v0v7_1v0v6_1v0v5_1v1v11_1v0v1_1v0v1/grdwindinversion/lib/python3.10/site-packages/rasterio/env.py", line 451, in wrapper
    return f(args, *kwds)
  File "/tmp/2024v2v1_0v9_0v2v3vpost6_1v0v7_1v0v6_1v0v5_1v1v11_1v0v1_1v0v1/grdwindinversion/lib/python3.10/site-packages/rasterio/init.py", line 304, in open
    dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
  File "rasterio/base.pyx", line 312, in rasterio.base.DatasetBase.__init
rasterio.errors.RasterioIOError: s1a-ew-grd-vv-20210930t205405-20210930t205434-039916-04b935-001.tiff: TIFFReadDirectory:Failed to read directory at offset 102684056

11/02/2024 18:56:11 ERROR inversion.py(494) s1a-ew-grd-vv-20210930t205405-20210930t205434-039916-04b935-001.tiff: TIFFReadDirectory:Failed to read directory at offset 102684056
```

**Comment by vincelhx** [comment]
Hi, 
still in error?

**Comment by agrouaze** [comment]
It is a corrupted SAFE, @Skealz do you have the permission to remove it and re download it?
