### ISSUE TITLE
Error interpolate in sentinel-1 reader

### ISSUE THREAD

**Issue by Skealz** [umr-lops/grdwindinversion#85]
```
29/10/2024 15:24:19 INFO main.py(37) input file: /home/datawork-cersat-public/cache/project/mpc-sentinel1/data/esa/sentinel-1a/L1/EW/S1A_EW_GRDH_1S/2014/158/S1A_EW_GRDH_1SDV_20140607T112346_20140607T112426_000943_000EA9_8664.SAFE
29/10/2024 15:24:20 WARNING inversion.py(559) Using meteorological convention because "winddir_convention" was not found in config.
29/10/2024 15:24:20 INFO inversion.py(589) recalibration is False : Kersten formula is not applied
29/10/2024 15:24:20 INFO utils.py(479) BlockingActorProxy: Transparent proxy for from_dict
/home/datawork-cersat-public/cache/project/sarwing/commits/xsar_2024v10v21_1v6_0v2v6_1v1v5_1v0v7_1v0v6_1v2v4_1v0v3_1v0v1_1v2v1/grdwindinversion/lib/python3.10/site-packages/numpy/core/numeric.py:407: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(res, fill_value, casting='unsafe')
29/10/2024 15:24:35 WARNING base_dataset.py(871) Raster variable are experimental
29/10/2024 15:24:36 INFO inversion.py(606) Traceback (most recent call last):
  File "/home/datawork-cersat-public/cache/project/sarwing/commits/xsar_2024v10v21_1v6_0v2v6_1v1v5_1v0v7_1v0v6_1v2v4_1v0v3_1v0v1_1v2v1/grdwindinversion/lib/python3.10/site-packages/grdwindinversion/inversion.py", line 592, in preprocess
    xsar_dataset = fct_dataset(
  File "/home/datawork-cersat-public/cache/project/sarwing/commits/xsar_2024v10v21_1v6_0v2v6_1v1v5_1v0v7_1v0v6_1v2v4_1v0v3_1v0v1_1v2v1/grdwindinversion/lib/python3.10/site-packages/xsar/sentinel1_dataset.py", line 298, in __init__
    self.add_high_resolution_variables(
  File "/home/datawork-cersat-public/cache/project/sarwing/commits/xsar_2024v10v21_1v6_0v2v6_1v1v5_1v0v7_1v0v6_1v2v4_1v0v3_1v0v1_1v2v1/grdwindinversion/lib/python3.10/site-packages/xsar/sentinel1_dataset.py", line 549, in add_high_resolution_variables
    self._dataset = self._dataset.merge(self.get_sensor_velocity())
  File "/home/datawork-cersat-public/cache/project/sarwing/commits/xsar_2024v10v21_1v6_0v2v6_1v1v5_1v0v7_1v0v6_1v2v4_1v0v3_1v0v1_1v2v1/grdwindinversion/lib/python3.10/site-packages/xsar/sentinel1_dataset.py", line 1479, in get_sensor_velocity
    _vels = interp_f(azimuth_times.astype(float))
  File "/home/datawork-cersat-public/cache/project/sarwing/commits/xsar_2024v10v21_1v6_0v2v6_1v1v5_1v0v7_1v0v6_1v2v4_1v0v3_1v0v1_1v2v1/grdwindinversion/lib/python3.10/site-packages/scipy/interpolate/_polyint.py", line 81, in __call__
    y = self._evaluate(x)
  File "/home/datawork-cersat-public/cache/project/sarwing/commits/xsar_2024v10v21_1v6_0v2v6_1v1v5_1v0v7_1v0v6_1v2v4_1v0v3_1v0v1_1v2v1/grdwindinversion/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 533, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/home/datawork-cersat-public/cache/project/sarwing/commits/xsar_2024v10v21_1v6_0v2v6_1v1v5_1v0v7_1v0v6_1v2v4_1v0v3_1v0v1_1v2v1/grdwindinversion/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 566, in _check_bounds
    raise ValueError(f"A value ({above_bounds_value}) in x_new is above "
ValueError: A value (1.4021402657135347e+18) in x_new is above the interpolation range's maximum value (1.402140265656e+18).

29/10/2024 15:24:36 ERROR inversion.py(607) A value (1.4021402657135347e+18) in x_new is above the interpolation range's maximum value (1.402140265656e+18).
```

**Comment by Skealz** [comment]
Maybe this should be opened in xsar...
